[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-cron"

  [plugins.inputs.crons]
  "*/15 * * * *" = "/.netlify/functions/meta-sync-cron"
